/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include <utility>

namespace bnb { namespace interfaces {

/**
 * User configurable parameters for in-CPU calculations during `FrameData`
 * processing. Meaning of this parameters are defined by features itself. 
 * Passed in list to `FrameData.addFeatureParameters`. 
 */
struct feature_parameter final {
    float x;
    float y;
    float z;
    float w;

    feature_parameter(float x_,
                      float y_,
                      float z_,
                      float w_)
    : x(std::move(x_))
    , y(std::move(y_))
    , z(std::move(z_))
    , w(std::move(w_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

