#pragma once

#include <bnb/effect_player/interfaces/camera_orientation.hpp>
#include <bnb/effect_player/interfaces/camera_poi_listener.hpp>
#include <bnb/effect_player/interfaces/color_range.hpp>
#include <bnb/effect_player/interfaces/color_std.hpp>
#include <bnb/effect_player/interfaces/consistency_mode.hpp>
#include <bnb/effect_player/interfaces/effect.hpp>
#include <bnb/effect_player/interfaces/effect_activated_listener.hpp>
#include <bnb/effect_player/interfaces/effect_activation_completion_listener.hpp>
#include <bnb/effect_player/interfaces/effect_event_listener.hpp>
#include <bnb/effect_player/interfaces/effect_info.hpp>
#include <bnb/effect_player/interfaces/effect_info_listener.hpp>
#include <bnb/effect_player/interfaces/effect_manager.hpp>
#include <bnb/effect_player/interfaces/effect_player.hpp>
#include <bnb/effect_player/interfaces/effect_player_configuration.hpp>
#include <bnb/effect_player/interfaces/effect_player_playback_state.hpp>
#include <bnb/effect_player/interfaces/effect_status.hpp>
#include <bnb/effect_player/interfaces/error_listener.hpp>
#include <bnb/effect_player/interfaces/face_number_listener.hpp>
#include <bnb/effect_player/interfaces/frame_data_listener.hpp>
#include <bnb/effect_player/interfaces/frame_duration_listener.hpp>
#include <bnb/effect_player/interfaces/frame_processor.hpp>
#include <bnb/effect_player/interfaces/hint_listener.hpp>
#include <bnb/effect_player/interfaces/input_manager.hpp>
#include <bnb/effect_player/interfaces/js_callback.hpp>
#include <bnb/effect_player/interfaces/low_light_listener.hpp>
#include <bnb/effect_player/interfaces/process_image_params.hpp>
#include <bnb/effect_player/interfaces/processor_configuration.hpp>
#include <bnb/effect_player/interfaces/processor_result.hpp>
#include <bnb/effect_player/interfaces/processor_status.hpp>
#include <bnb/effect_player/interfaces/processor_type.hpp>
#include <bnb/effect_player/interfaces/realtime_processor_mode.hpp>
#include <bnb/effect_player/interfaces/surface_data.hpp>
#include <bnb/effect_player/interfaces/types.hpp>
