/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <string>

namespace bnb { namespace interfaces {

/** Callback interface to receive effect activation notification */
class BNB_EXPORT effect_activation_completion_listener {
public:
    virtual ~effect_activation_completion_listener() {}

    /** called when effect is ready to use */
    virtual void on_effect_activation_finished(const std::string & url) = 0;
};

} }  // namespace bnb::interfaces
/// @}

