/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <cstdint>
#include <memory>

namespace bnb { namespace interfaces {

/** Configuration for EffectPlayer */
class BNB_EXPORT effect_player_configuration {
public:
    virtual ~effect_player_configuration() {}

    /**
     * @param fx_width Width of effect rendering area
     * @param fx_height Height of effect rendering area
     */
    static std::shared_ptr<effect_player_configuration> create(int32_t fx_width, int32_t fx_height);

    /** Init audio device. */
    virtual void set_audio_enabled(bool enabled) = 0;
};

} }  // namespace bnb::interfaces
/// @}

