/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class processor_status : int {
    /** Processed frame data */
    ok,
    /** Processor output buffer is empty */
    empty,
    /** Processing is skipped */
    skip,
    /** Error happen, check log */
    error,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::processor_status> {
    size_t operator()(::bnb::interfaces::processor_status type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

