/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <memory>

namespace bnb { namespace interfaces {

class BNB_EXPORT processor_configuration {
public:
    virtual ~processor_configuration() {}

    /** Create with default params */
    static std::shared_ptr<processor_configuration> create();

    /**
     * Use future frame filter, improves anti-jitter, adds processed frame inconsistency
     * Default: true
     */
    virtual void set_use_future_filter(bool value) = 0;

    /**
     * Use offline recognizer mode for processing
     * Default: false
     */
    virtual void set_use_offline_mode(bool value) = 0;
};

} }  // namespace bnb::interfaces
/// @}

