/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace bnb { namespace interfaces {

/** Data for creating surface */
struct surface_data final {
    /** Pointer to device gpu */
    int64_t gpu_device_ptr;
    /** Pointer to gpu command queue */
    int64_t command_queue_ptr;
    /** Pointer to render layer */
    int64_t surface_ptr;

    surface_data(int64_t gpu_device_ptr_,
                 int64_t command_queue_ptr_,
                 int64_t surface_ptr_)
    : gpu_device_ptr(std::move(gpu_device_ptr_))
    , command_queue_ptr(std::move(command_queue_ptr_))
    , surface_ptr(std::move(surface_ptr_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

