warp_hair = { inner = 10, outer = 200, mid = 0.1, strength = 0.15 }
warp_mesh = "Beauty06.bsm2"
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'matte_obj', 'mat_shadow', 'man40s_hat_mat', 'man40s_glasses_mat']

[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
selection_tex="redmask_new_3.png"
lookupTexTeeth="teeth_highlighter5.png"
lookupTexEyes="lut_80_percent.png"
tex_makeup="Face_Base_Color.ktx"

[materials.matte_obj]
vs = "vertex.vert"
fs = "nop.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = true
colorwrite = false
zwrite = true
shadow = false
samplers = {}

[materials.man40s_glasses_mat]
vs = "vertex.vert"
fs = "pbr_hdr.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.man40s_glasses_mat.samplers]
tex_diffuse="man40s_Base_Color.ktx"
tex_normal="man40s_Normal.ktx"
tex_mrao="man40s_MRAO.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

[materials.man40s_hat_mat]
vs = "vertex.vert"
fs = "pbr_hdr_hat.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.man40s_hat_mat.samplers]
tex_diffuse="man40s_Base_Color.ktx"
tex_normal="man40s_Normal.ktx"
tex_mrao="man40s_MRAO.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

# PBR
[materials.mat_shadow]
vs = "vertex.vert"
fs = "sprite.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.mat_shadow.samplers]
tex_diffuse="shadow.png"
