/// \file
/// \addtogroup Recognizer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from recognizer.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class recognizer_mode : int {
    /** Frame is processed only when pop_frame method called */
    synchronous,
    /** Frame processing begins on push_frame method call */
    asynchronous,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::recognizer_mode> {
    size_t operator()(::bnb::interfaces::recognizer_mode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

