/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#pragma once

#include <utility>
#include <vector>

namespace bnb { namespace interfaces {

struct camera_position final {
    std::vector<float> model_view_m;
    std::vector<float> projection_m;

    camera_position(std::vector<float> model_view_m_,
                    std::vector<float> projection_m_)
    : model_view_m(std::move(model_view_m_))
    , projection_m(std::move(projection_m_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

