/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#pragma once

#include <utility>
#include <vector>

namespace bnb { namespace interfaces {

/** Holds recognition result from an external source (ARKit, ARCore, etc.) */
struct external_face_data final {
    std::vector<float> vertices;
    std::vector<float> model_mat;
    std::vector<float> view_mat;
    std::vector<float> proj_mat;
    std::vector<float> landmarks;
    std::vector<bool> landmarks_mask;
    std::vector<float> landmarks_brows;
    std::vector<float> latents;

    external_face_data(std::vector<float> vertices_,
                       std::vector<float> model_mat_,
                       std::vector<float> view_mat_,
                       std::vector<float> proj_mat_,
                       std::vector<float> landmarks_,
                       std::vector<bool> landmarks_mask_,
                       std::vector<float> landmarks_brows_,
                       std::vector<float> latents_)
    : vertices(std::move(vertices_))
    , model_mat(std::move(model_mat_))
    , view_mat(std::move(view_mat_))
    , proj_mat(std::move(proj_mat_))
    , landmarks(std::move(landmarks_))
    , landmarks_mask(std::move(landmarks_mask_))
    , landmarks_brows(std::move(landmarks_brows_))
    , latents(std::move(latents_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

