/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#pragma once

#include "bnb/types/interfaces/eyes_corneosclera_mask.hpp"
#include "bnb/types/interfaces/eyes_iris_mask.hpp"
#include "bnb/types/interfaces/eyes_pupil_mask.hpp"
#include <utility>

namespace bnb { namespace interfaces {

struct eyes_mask final {
    eyes_iris_mask iris;
    eyes_corneosclera_mask corneosclera;
    eyes_pupil_mask pupil;

    eyes_mask(eyes_iris_mask iris_,
              eyes_corneosclera_mask corneosclera_,
              eyes_pupil_mask pupil_)
    : iris(std::move(iris_))
    , corneosclera(std::move(corneosclera_))
    , pupil(std::move(pupil_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

