/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace bnb { namespace interfaces {

struct size final {
    int32_t width;
    int32_t height;

    size(int32_t width_,
         int32_t height_)
    : width(std::move(width_))
    , height(std::move(height_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

