/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace bnb { namespace interfaces {

/**
 * User touch object.
 * Coordinate system is normalized to (-1, 1) with center in (0, 0).
 */
struct touch final {
    float x;
    float y;
    int64_t id;

    touch(float x_,
          float y_,
          int64_t id_)
    : x(std::move(x_))
    , y(std::move(y_))
    , id(std::move(id_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

