#pragma once

#include <bnb/scene/interfaces/animation_mode.hpp>
#include <bnb/scene/interfaces/asset_manager.hpp>
#include <bnb/scene/interfaces/attachment.hpp>
#include <bnb/scene/interfaces/attachment_info.hpp>
#include <bnb/scene/interfaces/attachment_load_op.hpp>
#include <bnb/scene/interfaces/attachment_store_op.hpp>
#include <bnb/scene/interfaces/attachment_type.hpp>
#include <bnb/scene/interfaces/audio_track.hpp>
#include <bnb/scene/interfaces/beauty_morphing.hpp>
#include <bnb/scene/interfaces/blending_mode.hpp>
#include <bnb/scene/interfaces/camera.hpp>
#include <bnb/scene/interfaces/camera_composer.hpp>
#include <bnb/scene/interfaces/camera_parameters.hpp>
#include <bnb/scene/interfaces/camera_texture.hpp>
#include <bnb/scene/interfaces/camera_texture_format.hpp>
#include <bnb/scene/interfaces/component.hpp>
#include <bnb/scene/interfaces/component_type.hpp>
#include <bnb/scene/interfaces/cubemap.hpp>
#include <bnb/scene/interfaces/entity.hpp>
#include <bnb/scene/interfaces/eyes_status.hpp>
#include <bnb/scene/interfaces/face.hpp>
#include <bnb/scene/interfaces/face_morphing.hpp>
#include <bnb/scene/interfaces/face_tracker.hpp>
#include <bnb/scene/interfaces/geometry_topology.hpp>
#include <bnb/scene/interfaces/gesture_type.hpp>
#include <bnb/scene/interfaces/hand.hpp>
#include <bnb/scene/interfaces/hand_tracker.hpp>
#include <bnb/scene/interfaces/hand_tracker_type.hpp>
#include <bnb/scene/interfaces/image.hpp>
#include <bnb/scene/interfaces/image_type.hpp>
#include <bnb/scene/interfaces/layer.hpp>
#include <bnb/scene/interfaces/mat2x4.hpp>
#include <bnb/scene/interfaces/mat3x4.hpp>
#include <bnb/scene/interfaces/mat4x4.hpp>
#include <bnb/scene/interfaces/material.hpp>
#include <bnb/scene/interfaces/media.hpp>
#include <bnb/scene/interfaces/mesh.hpp>
#include <bnb/scene/interfaces/mesh_instance.hpp>
#include <bnb/scene/interfaces/morphing.hpp>
#include <bnb/scene/interfaces/morphing_type.hpp>
#include <bnb/scene/interfaces/neuro_beautification_processed_texture.hpp>
#include <bnb/scene/interfaces/parameter.hpp>
#include <bnb/scene/interfaces/physics_simulator.hpp>
#include <bnb/scene/interfaces/pixel_format_type.hpp>
#include <bnb/scene/interfaces/procedural_algorithm_type.hpp>
#include <bnb/scene/interfaces/procedural_texture.hpp>
#include <bnb/scene/interfaces/projection_type.hpp>
#include <bnb/scene/interfaces/render_backend_type.hpp>
#include <bnb/scene/interfaces/render_info.hpp>
#include <bnb/scene/interfaces/render_list.hpp>
#include <bnb/scene/interfaces/render_target.hpp>
#include <bnb/scene/interfaces/resource.hpp>
#include <bnb/scene/interfaces/scene.hpp>
#include <bnb/scene/interfaces/segmentation_mask.hpp>
#include <bnb/scene/interfaces/segmentation_mask_type.hpp>
#include <bnb/scene/interfaces/shader_source.hpp>
#include <bnb/scene/interfaces/state.hpp>
#include <bnb/scene/interfaces/text_texture.hpp>
#include <bnb/scene/interfaces/texture.hpp>
#include <bnb/scene/interfaces/texture_filtering_mode.hpp>
#include <bnb/scene/interfaces/transformation_3d.hpp>
#include <bnb/scene/interfaces/trigger_status_type.hpp>
#include <bnb/scene/interfaces/trigger_type.hpp>
#include <bnb/scene/interfaces/vec3.hpp>
#include <bnb/scene/interfaces/vec4.hpp>
#include <bnb/scene/interfaces/video.hpp>
#include <bnb/scene/interfaces/video_loading_result_listener.hpp>
#include <bnb/scene/interfaces/weighted_lut.hpp>
#include <bnb/scene/interfaces/types.hpp>
