/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class attachment_load_op : int {
    /**
     * Don't care about attachment content at the pass 
     * start (pass will overwrite all pixels)
     */
    dont_care,
    /** Clear to `clear_color` at pass start */
    clear,
    /** load pixels from the previous frame */
    load,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::attachment_load_op> {
    size_t operator()(::bnb::interfaces::attachment_load_op type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

