/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class attachment_store_op : int {
    /**
     * Save pixels, to be read later by sampler 
     * or loaded in the next frame
     */
    save,
    /** No need to store pixels after pass finish */
    discard,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::attachment_store_op> {
    size_t operator()(::bnb::interfaces::attachment_store_op type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

