/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <utility>

namespace bnb { namespace interfaces {

struct eyes_status final {
    bool is_left_open;
    bool is_right_open;

    eyes_status(bool is_left_open_,
                bool is_right_open_)
    : is_left_open(std::move(is_left_open_))
    , is_right_open(std::move(is_right_open_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

