/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class image_type : int {
    attachment,
    cubemap,
    segmentation_mask,
    texture,
    camera_texture,
    video,
    weighted_lut,
    text_texture,
    procedural_texture,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::image_type> {
    size_t operator()(::bnb::interfaces::image_type type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

