/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <utility>

namespace bnb { namespace interfaces {

struct mat2x4 final {
    float m11;
    float m12;
    float m13;
    float m14;
    float m21;
    float m22;
    float m23;
    float m24;

    mat2x4(float m11_,
           float m12_,
           float m13_,
           float m14_,
           float m21_,
           float m22_,
           float m23_,
           float m24_)
    : m11(std::move(m11_))
    , m12(std::move(m12_))
    , m13(std::move(m13_))
    , m14(std::move(m14_))
    , m21(std::move(m21_))
    , m22(std::move(m22_))
    , m23(std::move(m23_))
    , m24(std::move(m24_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

