/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <string>
#include <unordered_map>

namespace bnb { namespace interfaces {

/** Class, which provide neural beautification algorithms adjust interface. */
class BNB_EXPORT neuro_beautification_processed_texture {
public:
    virtual ~neuro_beautification_processed_texture() {}

    /** Receive map with neural beautification parameters. */
    virtual void set_parameters(const std::unordered_map<std::string, std::string> & parameters) = 0;

    virtual std::unordered_map<std::string, std::string> get_parameters() const = 0;

    virtual void set_active(bool active) = 0;

    virtual bool is_active() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

