/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class pixel_format_type : int {
    r8,
    rg8,
    rgb8,
    rgba8,
    bgra8,
    r16f,
    rg16f,
    rgba16f,
    r32f,
    rgba32f,
    rgb10a2,
    depth16,
    depth24,
    depth32f,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::pixel_format_type> {
    size_t operator()(::bnb::interfaces::pixel_format_type type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

