/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <memory>

namespace bnb { namespace interfaces {

class image;
enum class segmentation_mask_type;

/**Class, which repesent neural networks segmentation mask texture interface. Subclass of image */
class BNB_EXPORT segmentation_mask {
public:
    virtual ~segmentation_mask() {}

    /**@return segmentation mask type. Can be background, hair, skin, lips, l_eye, r_eye. */
    virtual segmentation_mask_type get_mask_type() const = 0;

    /**
     *set segmentation mask activity flag
     *@param active (bool): segmentation mask activity flag
     */
    virtual void set_active(bool active) = 0;

    /**@return segmentation mask activity flag (bool). */
    virtual bool is_active() = 0;

    /**@return upcast to base type */
    virtual std::shared_ptr<image> as_image() = 0;
};

} }  // namespace bnb::interfaces
/// @}

