/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class segmentation_mask_type : int {
    background,
    hair,
    skin,
    lips,
    l_eye,
    r_eye,
    l_eye_pupil,
    r_eye_pupil,
    l_eye_corneosclera,
    r_eye_corneosclera,
    lips_shining,
    occlusion,
    body,
    hair_strand,
    neck,
    neck_smoothing,
    skin_smoothing,
    l_brow,
    r_brow,
    nails,
    face,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::segmentation_mask_type> {
    size_t operator()(::bnb::interfaces::segmentation_mask_type type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

