/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <string>
#include <utility>

namespace bnb { namespace interfaces {

struct shader_source final {
    std::string vs;
    std::string fs;

    shader_source(std::string vs_,
                  std::string fs_)
    : vs(std::move(vs_))
    , fs(std::move(fs_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

