/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <utility>

namespace bnb { namespace interfaces {

struct vec4 final {
    float x;
    float y;
    float z;
    float w;

    vec4(float x_,
         float y_,
         float z_,
         float w_)
    : x(std::move(x_))
    , y(std::move(y_))
    , z(std::move(z_))
    , w(std::move(w_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

