/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <memory>
#include <string>

namespace bnb { namespace interfaces {

class image;
class resource;

class BNB_EXPORT weighted_lut {
public:
    virtual ~weighted_lut() {}

    virtual void load_resource(const std::shared_ptr<resource> & res) = 0;

    virtual void set_weight(float value) = 0;

    virtual float get_weight() const = 0;

    virtual void load(const std::string & file_name) = 0;

    /**@return upcast to base type */
    virtual std::shared_ptr<image> as_image() = 0;
};

} }  // namespace bnb::interfaces
/// @}

