warp_mesh = "BeautyFace.bsm2"
warp_hair = { inner = 10, outer = 200, mid = 0.1, strength = 0.4 }
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'facemat', 'Elvis', 'Glass']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
lookupTexTeeth="lut3d_TEETH_high.png"
lookupTexEyes="lut3d_EYES_high.png"
tex_softLight="soft_princess.png"
tex_highlight="FLARE_40_768.png"

# Cut
[materials.facemat]
vs = "facemat.vert"
fs = "facemat.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.Elvis]
vs = "elvis.vert"
fs = "elvis.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
[materials.Elvis.samplers]
tex_diffuse="Elvis_BaseColor.png"
tex_normal="Elvis_Normal.png"
tex_metallic="Elvis_Metallic.png"
tex_roughness="Elvis_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

# PBR
[materials.Glass]
vs = "glass.vert"
fs = "glass_mat.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
[materials.Glass.samplers]
tex_diffuse="Elvis_BaseColor.png"
tex_normal="Elvis_Normal.png"
tex_metallic="Elvis_Metallic.png"
tex_roughness="Elvis_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
