warp_mesh = "Face_05.bsm2"
msaa = 1
shadowmap_size = 512
draw_order = ['retouch', 'cut', 'hat', 'glass', 'teeth']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
selection_tex="redmask_new_3.png"
lookupTexTeeth="teeth_highlighter5.png"
lookupTexEyes="eyes_middle.png"
tex_softLight="soft.png"
tex_normalMakeup="MakeUp.png"
tex_highlight="37.png"

# PBR
[materials.cut]
vs = "cut.vert"
fs = "cut.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = true
[materials.cut.samplers]
tex_diffuse="no_Base_Color.png"
tex_normal="no_Normal.png"
tex_metallic="no_Metallic.png"
tex_roughness="no_Roughness.png"

# PBR
[materials.hat]
vs = "hat.vert"
fs = "hat.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = true
[materials.hat.samplers]
tex_diffuse="hat_BaseColor.png"
tex_normal="hat_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="hat_MRAO.ktx"

# PBR
[materials.glass]
vs = "glass.vert"
fs = "glass.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = true
[materials.glass.samplers]
tex_diffuse="hat_BaseColor.png"
tex_normal="glass_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="glass_MRAO.ktx"

# PBR
[materials.teeth]
vs = "teeth.vert"
fs = "hat.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = true
[materials.teeth.samplers]
tex_diffuse="hat_BaseColor.png"
tex_normal="hat_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="hat_MRAO.ktx"