warp_mesh = "face_01.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'shadow', 'cut', 'face', 'hat', 'tobacco', 'Plane_mat']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
lookupTexTeeth="lut3d_TEETH_medium.png"
lookupTexEyes="lut3d_EYES_medium.png"
tex_softLight="face_Base_Color.ktx"

# PBR
[materials.shadow]
vs = "shadow.vert"
fs = "shadow.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.shadow.samplers]
tex_diffuse="hat_Base_Color.ktx"
tex_normal="hat_Normal.ktx"
tex_mrao="hat_MRAO.ktx"

# Cut
[materials.cut]
vs = "cut.vert"
fs = "cut.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# Cut
[materials.face]
vs = "face.vert"
fs = "face.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.hat]
vs = "hat.vert"
fs = "hat.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.hat.samplers]
tex_diffuse="hat_Base_Color.ktx"
tex_normal="hat_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="hat_MRAO.ktx"

# PBR
[materials.tobacco]
vs = "tobacco.vert"
fs = "tobacco.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.tobacco.samplers]
tex_diffuse="hat_Base_Color.ktx"
tex_normal="hat_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="hat_MRAO.ktx"

# PBR
[materials.Plane_mat]
vs = "plane_mat.vert"
fs = "video.frag"
blend = "screen"
backfaces = true
shadow = false
zwrite = false
samplers = {}

