draw_order = ["retouch", "!glfx_WARP_IMAGE", "Default", "hat", "glass"]
warp_mesh = "Morph.bsm2"
shadowmap_size = 512

[materials]

[materials.Default]
fs = "default.frag"
colorwrite = false
backfaces = false
vs = "default.vert"
zwrite = true
shadow = true
blend = "off"

[materials.Default.samplers]
tex_normal = "Default_Normal.ktx"
tex_diffuse = "Default_Base_Color.ktx"
tex_mrao = "Default_MRAO.ktx"

[materials.glass]
fs = "glass.frag"
colorwrite = true
backfaces = false
vs = "glass.vert"
zwrite = true
shadow = true
blend = "alpha"

[materials.glass.samplers]
tex_diffuse = "glass_Base_Color.ktx"
tex_normal = "glass_Normal.ktx"
tex_mrao = "glass_MRAO.ktx"
tex_brdf = "brdf.ktx"
tex_ibl_diff = "ibl_diff.ktx"
tex_ibl_spec = "ibl_spec.ktx"

[materials.retouch]
fs = "retouch.frag"
colorwrite = true
backfaces = false
vs = "retouch.vert"
mouth = true
zwrite = true
onface = true
shadow = false
blend = "off"

[materials.retouch.samplers]
lookupTexEyes = "lut_80_percent.png"
tex_softLight = "softlight.png"
lookupTexTeeth = "teeth_highlighter5.png"
tex_normalMakeup = "makeup.png"
selection_tex = "redmask_new_3.png"
tex_highlight = "flare66.png"

# PBR
[materials.hat]
vs = "hat.vert"
fs = "hat.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
[materials.hat.samplers]
tex_diffuse = "glass_Base_Color.ktx"
tex_normal = "glass_Normal.ktx"
tex_mrao = "glass_MRAO.ktx"
