/// \file
/// \addtogroup Utils
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from utils.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <cstdint>
#include <memory>

namespace bnb { namespace interfaces {

class BNB_EXPORT egl_context {
public:
    virtual ~egl_context() {}

    static std::shared_ptr<egl_context> create(int32_t width, int32_t height);

    virtual bool check() const = 0;

    virtual void activate() const = 0;

    virtual void deactivate() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

